### ISSUE TITLE
Home Page functionalities

### ISSUE THREAD

**Issue by Sunny619** [Sunny619/Meta-Call#5]
1. Create a logo for metacall.
2. Design the homepage
3. Create a proper route for joining a room
4. Add room join custom and default URL functionality.
5. Create an input for username and pass the chosen name to the room and update it

**Comment by Fr0stb1t3** [comment]
HomePage design done.
Route to be created through expressjs.

**Comment by Fr0stb1t3** [comment]
Completed. Check Modularization
